const currentColorDefault='#3f38cd'
export const signOutStyle=StyleSheet.create({
    backGroundApp:{
        position:'relative',
        zIndex:10,
        backgroundColor:'#888',
        height:'100%',
        width:'100%',
        flexDirection:'row',
    },
    frame1:{
        backgroundColor:'#FFF',
        height:'100%',
        width:'50%'
    },
    frame2:{
        backgroundColor:currentColorDefault,
        height:'100%',
        width:'50%'
    },
    overBackground:{
        position:'absolute',
        zIndex:20,
        height:'100vh',
        width:'100vw'
    },
    titleContainer:{
        height:'20vh',
        width:'100%',
        backgroundColor:currentColorDefault,
        borderBottomLeftRadius:125
    },
    formContainer:{
        height:'80vh',
        width:'100%',
        fontFamily:'sans-serif',
        backgroundColor:'#FFF',
        borderTopRightRadius:125,
        paddingLeft:50,
        paddingTop:25
    },
    tittle:{
        fontSize:150,
        fontWeight:'bold',
        fontFamily:'sans-serif',
        color:'#525252',
        paddingBottom:'none',
        backgroundColor:'#333'
    },
    subTitle:{
        fontSize:50,
        fontWeight:'bold',
        fontFamily:'sans-serif',
        color:'#929282'
    }
})
